### ISSUE TITLE
The exported.obj has no texture

### ISSUE THREAD

**Issue by stepstep123** [wyysf-98/Sin3DGen#2]
Thanks for your nice work! 
When I loaded the exported obj with blender, it had no texture. how  can i  export the obj with textures or get a separate.mtl file. 
Thanks again.

**Comment by wyysf-98** [comment]
Thanks for your interest.
We use Plenoxels(https://github.com/sxyu/svox2) as the scene representation. It uses sh coefficients (https://en.wikipedia.org/wiki/Spherical_harmonics) to represent the appearance, resulting in photorealistic rendering results. Extracting texture from Plenoxels is a challenging task as it is hard to convert sh coefs to RGB, and will significantly degrade performance. Therefore, we only extract meshes in this work. However, we are currently working on adapting our method to the current graphics workflow using mesh as a representation with texture.

BTW, You can change the N_grid here https://github.com/wyysf-98/Sin3DGen/blob/main/utils/plenoxels_wrapper.py#L475 to get a more detailed mesh.

**Comment by stepstep123** [comment]
> 
Thank you for your reply.
Exactly, the larger the N_grid, the more detailed it is. 
Except new artwork.
