### ISSUE TITLE
Questions about usage

### ISSUE THREAD

**Issue by Asianfleet** [wyysf-98/Sin3DGen#5]
1. The 3D mesh output doesn't have color.How can I get textured 3D mesh ?
2. It seems that the released code does't include 3D editing function ,which is mentioned in the project page.Can it be supported in the future?

**Comment by wyysf-98** [comment]
Hi, THX for your interest in our work. 
1. As we use NeRF-like representation to represent the 3D scenes for better visual quality, it is non-trivial to convert this representation into texture mesh (https://github.com/wyysf-98/Sin3DGen/issues/2#issuecomment-1582067759).  Or you can try this work (https://github.com/Sin3DM/Sin3DM) to generate textured meshes from a single example.
2. 3D editing requires some manual participation, such as manually specifying the editing area. It might be difficult to have a simpler way to interact, so we don't provide it in the current code.
I think you can quickly try to hack the code here (https://github.com/wyysf-98/Sin3DGen/blob/main/generate.py#L212) to achieve these functions, and don't need to modify the core code.
